package RESTAURENTMANAGEMENT.view;

public enum ManagerOptions {
    ADD_TABLENUMBER,
    REMOVE_TABLENUMBER,
    ADD_ITEMS,
    ALTER_FOODPRICE,
    DELETE_ITEM,
    CREATE_NEW_MENU,
    SET_TIMING,
    EXIT;
}
